#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias ls="ls -G"
alias vo="vim -R"
alias todo="vim /home/richard/.todo.etd"
alias vi="vim"
alias lchg="svn di -rPREV:HEAD"
alias post-review="post-review --target-groups=xy2_server"
alias ll="ls -alh"
alias te="tail log/sys/error.dat"
alias tl="tail log/debug.log"
alias t="tmux"
alias tt="tmux attach -t"
alias to="teamocil"

if [[ $(uname) == "FreeBSD" ]]; then
  export LANG="zh_CN.GB18030"
elif [[ $(uname) == "Darwin" ]]; then
  export LANG="zh_CN.UTF-8"
else
  export LANG="zh_CN.UTF-8"
fi

export GIT_EDITOR=vim
export PYTHONDONTWRITEBYTECODE=x
export SVN_EDITOR=vim
export EDITOR=vim

export PATH=$HOME/bin:/opt/local/bin:$PATH

snet() {
	macsnet.py ssh $@
	if [ -f "/tmp/richard_macsnet.cmd" ]
	then
		cmd=`head -n1 /tmp/richard_macsnet.cmd`
		rm -f /tmp/richard_macsnet.cmd
		eval $cmd
	fi
}

fnet() {
	macsnet.py sftp $@
	if [ -f "/tmp/richard_macsnet.cmd" ]
	then
		cmd=`head -n1 /tmp/richard_macsnet.cmd`
		rm -f /tmp/richard_macsnet.cmd
		eval $cmd
	fi
}

[[ -s "${ZDOTDIR:-$HOME}/.autojump/etc/profile.d/autojump.sh" ]] && source "${ZDOTDIR:-$HOME}/.autojump/etc/profile.d/autojump.sh"

autoload -U compinit && compinit -u

#export LSCOLORS=gxfxbEaEBxxEhEhBaDaCaD
if [ -d "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages" ]
then
	export PYTHONPATH="$PYTHONPATH:/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages"
fi

compctl -g '~/.teamocil/*(:t:r)' teamocil
